### ISSUE TITLE
EPIC: Moar tests

### ISSUE THREAD

**Issue by nic547** [nic547/TauStellwerk#102]
As a developer, I would like to have a high test coverage so that I can have high confidence that my software still performs correctly after a given change. 

Integration test with TauStellwerk.Server and TauStellwerk.Client
- [x] #108
- [x] Integration tests for engine control

Unit tests:
- [ ] Unit tests for WebClient (If possible, might need some architectural improvements)
- [ ] Unit tests for  TauStellwerk.Client Lib
- [ ]  Unit tests for TauStellwerk.Desktop
- [ ] More unit tests for the ECoS implemtation

The goal would be to reach 80% code coverage or better for now.
